### ISSUE TITLE
Convert images to Equirectangular

### ISSUE THREAD

**Issue by NicolaPavan** [bhautikj/vrProjector#7]
Hi, very interesting your tool.
I'm use it in mac os with terminal, I'm not a developer and I think to has installed all PreRequisites but with this command line: 
'sudo ./vrProjectorCmd --sourceProjection Cubemap --sourceImage images/"front.png right.png back.png left.png top.png bottom.png" --sourceImage true --outProjection Equirectangular --outImage Prova1.png --outWidth 6000 --outHeight 3000'
The Terminal shell print: 
'Traceback (most recent call last):
  File "vrProjectorWrapper.py", line 72, in <module>
    main()
  File "vrProjectorWrapper.py", line 39, in main
    source.loadImages(imageList[0], imageList[1], imageList[2], imageList[3], imageList[4], imageList[5])
IndexError: list index out of range'

Where is my error? Thanks however Nice Job ;)

**Comment by bhautikj** [comment]
Error is in the `sourceImage` argument. The command-line should be:
`sudo ./vrProjectorCmd --sourceProjection Cubemap --sourceImage images/front.png images/right.png images/back.png images/left.png images/top.png images/bottom.png --sourceImage true --outProjection Equirectangular --outImage Prova1.png --outWidth 6000 --outHeight 3000`
