### ISSUE TITLE
Error at: parsed.paste(img, mask=img.split()[3]) for images with 3 bands

### ISSUE THREAD

**Issue by peterlitvak** [bhautikj/vrProjector#8]
Suggested change:
```
bands = img.split()
parsed.paste(img, mask=(bands[3] if len(bands) == 4 else None))
```
I'd do a pull request but I'm using a different source code formatting and it will not merge nicely unfortunately :(

**Comment by jukebox1412** [comment]
Totally fixed my issues! Thanks!

**Comment by Prithvi-Devaiah** [comment]
bands = img.split() throws
IndexError: tuple index out of range
Could you please help me out with this.
Thank you.

**Comment by bhautikj** [comment]
Thanks! Fix is pending in https://github.com/bhautikj/vrProjector/pull/9

**Comment by bhautikj** [comment]
Merged - thanks for the fix!
